version: '3'
services:
  gateway:
    build:
      context: ./gateway
    ports:
      - "5000:5000"
  cnpjservice:
    build:
      context: ./cnpj_service
    ports:
      - "5001:5000"
  cpfservice:
    build:
      context: ./cpf_service
    ports:
      - "5002:5000"
  institutionservice:
    build:
      context: ./institution_service
    ports:
      - "5003:5000"
  delegateservice:
    build:
      context: ./delegate_service
    ports:
      - "5004:5000"